//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindSyncApp.Resources.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindSyncApp.Resources.Locale.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string AlertDate {
            get {
                return ResourceManager.GetString("AlertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string AlertId {
            get {
                return ResourceManager.GetString("AlertId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string AlertMessage {
            get {
                return ResourceManager.GetString("AlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string AlertStatus {
            get {
                return ResourceManager.GetString("AlertStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Alerts.
        /// </summary>
        internal static string AlertsTitle {
            get {
                return ResourceManager.GetString("AlertsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ProfileChangeLanguage {
            get {
                return ResourceManager.GetString("ProfileChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string ProfileEmail {
            get {
                return ResourceManager.GetString("ProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ProfileLogout {
            get {
                return ResourceManager.GetString("ProfileLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string ProfileUsername {
            get {
                return ResourceManager.GetString("ProfileUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string TabsAlerts {
            get {
                return ResourceManager.GetString("TabsAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabsProfile {
            get {
                return ResourceManager.GetString("TabsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbines.
        /// </summary>
        internal static string TabsTurbines {
            get {
                return ResourceManager.GetString("TabsTurbines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude:.
        /// </summary>
        internal static string TurbineAltitude {
            get {
                return ResourceManager.GetString("TurbineAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string TurbineDataDate {
            get {
                return ResourceManager.GetString("TurbineDataDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power output:.
        /// </summary>
        internal static string TurbineDataPowerOutput {
            get {
                return ResourceManager.GetString("TurbineDataPowerOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated power:.
        /// </summary>
        internal static string TurbineDataRatedPower {
            get {
                return ResourceManager.GetString("TurbineDataRatedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine Data.
        /// </summary>
        internal static string TurbineDataTitle {
            get {
                return ResourceManager.GetString("TurbineDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed:.
        /// </summary>
        internal static string TurbineDataWindSpeed {
            get {
                return ResourceManager.GetString("TurbineDataWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine Details.
        /// </summary>
        internal static string TurbineDetailsTitle {
            get {
                return ResourceManager.GetString("TurbineDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency:.
        /// </summary>
        internal static string TurbineEfficiency {
            get {
                return ResourceManager.GetString("TurbineEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string TurbineId {
            get {
                return ResourceManager.GetString("TurbineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        internal static string TurbineLatitude {
            get {
                return ResourceManager.GetString("TurbineLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        internal static string TurbineLongitude {
            get {
                return ResourceManager.GetString("TurbineLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius:.
        /// </summary>
        internal static string TurbineRadius {
            get {
                return ResourceManager.GetString("TurbineRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string TurbineStatus {
            get {
                return ResourceManager.GetString("TurbineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Turbines.
        /// </summary>
        internal static string TurbinesTitle {
            get {
                return ResourceManager.GetString("TurbinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept area:.
        /// </summary>
        internal static string TurbineSweptArea {
            get {
                return ResourceManager.GetString("TurbineSweptArea", resourceCulture);
            }
        }
    }
}
